vich_uploader:
    db_driver: orm
    mappings:
        livre_photo:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            delete_on_remove: true
            delete_on_update: false
